name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  github-token:
    description: 'GitHub Token'
    required: true
  message:
    description: 'Message displayed in pr comment'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
